test-generator:
    template-directory: src/main/resources/templates
    test-template: spockTest.template

logging:
    level:
        root: INFO
        org:
            hobsoft:
                spring:
                    resttemplatelogger:
                        LoggingCustomizer: DEBUG  # Set to DEBUG to see JSON payloads sent/received on REST calls

swagger:
    enable: true
